"""Committed evidence artifacts for the C-MAPSS conformal prediction study.

Every number quoted in the writeup is written by this module into
``artifacts/conformal/``, which is git-tracked on purpose: a claim that traces
to prose is an attestation, and this repository is submitted as evidence of
method. `tests/test_conformal_artifacts_tracked.py` fails if the tracking is
ever removed.
"""

from __future__ import annotations

import csv
import math
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from aerospace_prognostics.artifact_io import prepare_output_path, write_json_payload
from aerospace_prognostics.experiments.cmapss_conformal import (
    CmapssConformalSeedSweep,
    CmapssConformalStudy,
)

CONFORMAL_ARTIFACT_DIRECTORY = Path("artifacts/conformal")


@dataclass(frozen=True)
class CmapssConformalEvidence:
    """Paths written for one conformal evidence bundle."""

    json_path: Path
    variants_csv_path: Path
    markdown_path: Path
    seed_sweep_csv_path: Path | None = None
    attainability_csv_path: Path | None = None


def write_cmapss_conformal_evidence(
    study: CmapssConformalStudy,
    *,
    output_directory: str | Path = CONFORMAL_ARTIFACT_DIRECTORY,
    seed_sweep: CmapssConformalSeedSweep | None = None,
    attainability_rows: Sequence[dict[str, float | int | str | bool]] | None = None,
    stem: str | None = None,
) -> CmapssConformalEvidence:
    """Write the JSON, CSV, and Markdown evidence for one conformal run."""
    directory = Path(output_directory)
    prefix = stem or f"cmapss_{study.population.subset.lower()}_conformal"

    payload: dict[str, object] = dict(study.to_dict())
    if seed_sweep is not None:
        payload["seed_sweep"] = seed_sweep.to_dict()
    if attainability_rows is not None:
        payload["attainability"] = list(attainability_rows)

    json_path = write_json_payload(_finite_json(payload), directory / f"{prefix}.json")
    variants_csv_path = _write_rows(
        [variant.to_row() for variant in study.variants],
        directory / f"{prefix}_variants.csv",
    )
    seed_sweep_csv_path = None
    if seed_sweep is not None:
        seed_sweep_csv_path = _write_rows(
            [summary.to_dict() for summary in seed_sweep.summaries],
            directory / f"{prefix}_seed_sweep.csv",
        )
    attainability_csv_path = None
    if attainability_rows:
        attainability_csv_path = _write_rows(
            list(attainability_rows),
            directory / f"{prefix}_attainability.csv",
        )
    markdown_path = _write_markdown(
        study,
        directory / f"{prefix}.md",
        seed_sweep=seed_sweep,
        attainability_rows=attainability_rows,
    )

    return CmapssConformalEvidence(
        json_path=json_path,
        variants_csv_path=variants_csv_path,
        markdown_path=markdown_path,
        seed_sweep_csv_path=seed_sweep_csv_path,
        attainability_csv_path=attainability_csv_path,
    )


def _write_rows(
    rows: Sequence[dict[str, float | int | str | bool]],
    path: str | Path,
) -> Path:
    if not rows:
        raise ValueError("at least one row is required")
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    output_path = prepare_output_path(path)
    with output_path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames, restval="")
        writer.writeheader()
        writer.writerows(rows)
    return output_path


def _write_markdown(
    study: CmapssConformalStudy,
    path: str | Path,
    *,
    seed_sweep: CmapssConformalSeedSweep | None,
    attainability_rows: Sequence[dict[str, float | int | str | bool]] | None,
) -> Path:
    population = study.population
    lines: list[str] = [
        f"# C-MAPSS {population.subset} Conformal Prediction Evidence",
        "",
        "Generated by `aerospace-prognostics cmapss-conformal`. Every figure in the "
        "writeup that concerns conformal intervals is read from this bundle.",
        "",
        "## Population",
        "",
        "| Field | Value |",
        "|---|---|",
    ]
    for key, value in population.to_dict().items():
        lines.append(f"| `{key}` | `{value}` |")

    lines += [
        "",
        "## Coverage And Width By Calibration Design",
        "",
        "Coverage is reported beside width in every row. A coverage figure on its own "
        "is satisfiable by an interval so wide it says nothing, and the "
        "`pooled_full_trajectory` row below is exactly that case.",
        "",
        "| Design | Unit-grouped | Scores | Radius | Width | Coverage | Nominal | "
        "Uncovered | Informative |",
        "|---|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for variant in study.variants:
        row = variant.to_row()
        lines.append(
            "| `{design}` | {unit_grouped} | {calibration_scores} | {interval_radius} | "
            "{interval_width} | {empirical_coverage} | {nominal_coverage} | "
            "{uncovered_points} | {is_informative}{reason} |".format(
                reason=(
                    f" ({row['uninformative_reason']})" if row["uninformative_reason"] else ""
                ),
                **{key: _render(value) for key, value in row.items()},
            )
        )

    lines += [
        "",
        f"Label-only reference width at this confidence: "
        f"`{_render(study.label_only_reference_width)}`. An interval at least this wide "
        "has added nothing to what the label distribution already said.",
        "",
    ]

    if study.subgroups:
        lines += [
            "## Primary Design, By Test Subgroup",
            "",
            "| Subgroup | Definition | Units | Coverage | Uncovered | Width |",
            "|---|---|---:|---:|---:|---:|",
        ]
        for subgroup in study.subgroups:
            row = subgroup.to_row()
            lines.append(
                "| `{subgroup}` | {definition} | {evaluation_units} | {empirical_coverage} | "
                "{uncovered_points} | {interval_width} |".format(
                    **{key: _render(value) for key, value in row.items()}
                )
            )
        lines.append("")

    if seed_sweep is not None:
        lines += [
            "## Repeated Unit Splits",
            "",
            f"Conformal coverage is a statement about repeated exchangeable draws. "
            f"These are `{len(seed_sweep.seeds)}` independent unit splits, each "
            f"retrained from scratch, at nominal `{_render(1.0 - seed_sweep.alpha)}`.",
            "",
            "| Design | Splits | Mean coverage | Min | Max | Mean width | "
            "Splits at or above nominal |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
        for summary in seed_sweep.summaries:
            row = summary.to_dict()
            lines.append(
                "| `{design}` | {seeds} | {mean_empirical_coverage} | "
                "{min_empirical_coverage} | {max_empirical_coverage} | "
                "{mean_interval_width} | {splits_meeting_nominal} |".format(
                    **{key: _render(value) for key, value in row.items()}
                )
            )
        lines.append("")

    if attainability_rows:
        lines += [
            "## Attainability Of A Confidence Level",
            "",
            "The rank is `ceil((n + 1)(1 - alpha))` and there is no `(n + 1)`-th order "
            "statistic among `n` scores, so `1 - alpha` is attainable only when "
            "`n >= 1/alpha - 1`. Calibration units must also be units the model was not "
            "trained on, so the fleet size caps the confidence level regardless of the model.",
            "",
        ]
        fieldnames = list(attainability_rows[0])
        lines.append("| " + " | ".join(f"`{name}`" for name in fieldnames) + " |")
        lines.append("|" + "---|" * len(fieldnames))
        for row in attainability_rows:
            lines.append(
                "| " + " | ".join(_render(row.get(name, "")) for name in fieldnames) + " |"
            )
        lines.append("")

    output_path = prepare_output_path(path)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


def _render(value: object) -> str:
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        if math.isinf(value):
            return "inf"
        return f"{value:.6f}"
    return str(value)


def _finite_json(value: object) -> object:
    """Replace infinities with the string ``"inf"`` before serialising.

    An unattainable confidence level produces a genuinely infinite radius, and
    that is a result worth committing rather than an error to suppress. Python's
    `json` would write it as the bare token `Infinity`, which is not valid JSON
    and which several readers reject outright, so it is recorded as text.
    """
    if isinstance(value, dict):
        return {key: _finite_json(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_finite_json(item) for item in value]
    if isinstance(value, float) and not math.isfinite(value):
        return "inf" if value > 0 else "-inf"
    return value
